name: Visage Deploy

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd client
    - run: npm install
    - run: npm run build
    - run: cd ../server
    - run: npm install
    - run: npm run start
